geode-sdk/geode

- SDK/BuildFiles/gen/data/GeometryDash.bro
> fixed modlistview lagging, crashing and looking fucky

- kit/gen/data/GeometryDash.bro
these have NOT been tested in geode yet but I am fairly certain that they are correct
> add more known addresses for windows

- kit/gen/data/GeometryDash.bro
> Make singleton shared states static

- kit/gen/data/GeometryDash.bro
> Add some LevelInfoLayer and InfoLayer callbacks

- kit/gen/data/GeometryDash.bro
> Added some more MenuLayer function adresses

- kit/gen/data/GeometryDash.bro
> More MenuLayer adresses (updated)

- bindings/GeometryDash.bro
adds some missing windows addresses to GeometryDash.bro
args/returns of newly added functions *might* be wrong but i think they're right
> add some windows addresses

- bindings/GeometryDash.bro
fixed the windows PlayLayer::markCheckpoint address because it pointed to UILayer::onCheck;
> Fix the windows PlayLayer::markCheckpoint address

- loader/include/Geode/loader/Log.hpp
- loader/include/Geode/utils/JsonValidation.hpp
- loader/include/Geode/utils/addresser.hpp
- loader/src/hooks/MessageBoxFix.cpp
- loader/src/index/Index.cpp
- loader/src/index/InstallTicket.cpp
- loader/src/load/Hook.cpp
- loader/src/load/Loader.cpp
- loader/src/load/Log.cpp
- loader/src/load/Mod.cpp
- loader/src/ui/nodes/MDTextArea.cpp
> UI new log

- cmake/GeodeFile.cmake
- loader/include/Geode/loader/Setting.hpp
- loader/include/Geode/utils/cocos.hpp
- loader/src/ui/internal/info/ModInfoLayer.cpp
- loader/src/ui/internal/info/ModInfoLayer.hpp
- loader/src/ui/internal/list/ModListLayer.cpp
- loader/src/ui/internal/list/ModListLayer.hpp
- loader/src/ui/internal/list/SearchFilterPopup.cpp
- loader/src/ui/internal/list/SearchFilterPopup.hpp
- loader/src/ui/internal/settings/GeodeSettingNode.cpp
- loader/src/ui/internal/settings/GeodeSettingNode.hpp
- loader/src/ui/internal/settings/ModSettingsPopup.cpp
- loader/src/ui/internal/settings/ModSettingsPopup.hpp
rip makeMenuSelector your will be missed 🙏
> deprecate makeMenuSelector and replace all uses with actual member functions ;-;

- bindings/GeometryDash.bro
> Add delegates to EditLevelLayer

- README.md
I make the most minimal PRs ever
> I'm not a regular Nazi, just a grammar Nazi 

- .clang-format
- bindings/GeometryDash.bro
- codegen/src/ModifyGen.cpp
- loader/include/Geode/loader/Loader.hpp
- loader/include/Geode/modify/Field.hpp
- loader/include/Geode/modify/InternalMacros.hpp
- loader/include/Geode/modify/Modify.hpp
- loader/include/Geode/utils/casts.hpp
- loader/src/hooks/GeodeNodeMetadata.cpp
- loader/src/hooks/LevelSearchLayer.cpp
- loader/src/hooks/LoadingLayer.cpp
- loader/src/hooks/MenuLayer.cpp
- loader/src/hooks/TouchDispatcherFix.cpp
- loader/src/hooks/handler_fixes.cpp
- loader/src/hooks/persist.cpp
- loader/src/hooks/save.cpp
- loader/src/hooks/update.cpp
- loader/src/hooks/updateResources.cpp
- loader/src/internal/InternalLoader.cpp
- loader/src/ui/nodes/TextRenderer.cpp
- loader/src/utils/convert.cpp
- loader/test/dependency/main.cpp
- loader/test/main/main.cpp
The $modify macro is still there and supported.
> Implement a new modify syntax that doesn't require a macro and make Geode Loader use it 

- .github/workflows/test-offsets.yml
- bindings/GeometryDash.bro
- loader/test/members/Common.hpp
- loader/test/members/Windows.cpp
also adds some offsets for windows
> Add CI for member tests, fix PlayerObject

- bindings/GeometryDash.bro
> Add definitions related to level rating stats

- bindings/GeometryDash.bro
Added bindings for `GJUserMessage`, `GJMapPack`, `MapPackCell`, `GJMessageCell`,  `LevelTools`, `SetIDPopup`,  `AchievementCell`, `GooglePlayManager`
> Add more bindings

- .gitignore
- bindings/GeometryDash.bro
> add EditorUI::moveObjectCall(EditCommand)

- loader/include/Geode/utils/cocos.hpp
> Fix CCDictionaryExt's `=` operator

- CMakeLists.txt
- bindings/Cocos2d.bro
- bindings/GeometryDash.bro
- codegen/src/BindingGen.cpp
- loader/include/Geode/cocos/CCScheduler.h
- loader/include/Geode/cocos/base_nodes/CCNode.h
- loader/include/Geode/cocos/cocoa/CCObject.h
- loader/include/Geode/cocos/layers_scenes_transitions_nodes/CCScene.h
- loader/include/Geode/cocos/platform/win32/CCApplication.h
- loader/include/Geode/cocos/platform/win32/CCEGLView.h
- loader/include/Geode/cocos/touch_dispatcher/CCTouchDispatcher.h
- loader/include/Geode/loader/Event.hpp
- loader/include/Geode/loader/Log.hpp
- loader/include/Geode/ui/BasedButtonSprite.hpp
- loader/include/Geode/utils/cocos.hpp
- loader/src/cocos2d-ext/Getters.cpp
- loader/src/cocos2d-ext/Layout.cpp
- loader/src/hooks/GeodeNodeMetadata.cpp
- loader/src/loader/Event.cpp
- loader/src/loader/Mod.cpp
- loader/src/ui/nodes/BasedButtonSprite.cpp
- loader/src/ui/nodes/Scrollbar.cpp
- loader/src/utils/cocos.cpp
- loader/test/members/CMakeLists.txt
Adds new event listener-related stuff, such as `CCNode::addEventListener` (shorthand utility for adding a `CCNode`-targeting event listener), as well as make event listeners public to allow mods to sort them. Also tons of unrelated stuff because I'm silly
> Event stuff

- bindings/GeometryDash.bro
- loader/src/ids/CustomSongWidget.cpp
Did some commits with another email, oops. I added the mac binding.
> init binding and string ids for CustomSongWidget

- bindings/GeometryDash.bro
> Rename m_unk2AC in GJBaseGameLayer to m_activeEnterEffect

- CMakeLists.txt
> update json library

- bindings/GeometryDash.bro
was gamemanager::update for some reason
> fix gameobject::update addr

- bindings/Cocos2d.bro
- loader/include/Geode/cocos/particle_nodes/CCParticleSystem.h
> Add modify to CCParticleSystem and fix removed field

- loader/include/Geode/loader/Mod.hpp
this should be `key` instead of `sett`
> Fix Mod::setSettingValue

- bindings/GeometryDash.bro
- loader/include/Geode/Enums.hpp
- Corrected UserListType enum
- Added UserListDelegate class
- Added FriendsProfilePage binding (create & init functions)
> added FriendsProfilePage

- EULA
the first 2 separators containing one more "=" character than the rest wasn't being very kind to my ocd so I had to change it, I know it's like the most unimportant change ever but still
> change separator length

- .github/workflows/build-android.yml
put it in a separate file cuz too lazy
> Android ci

- bindings/GeometryDash.bro
I'm not entirely sure what they're for, I simply found that they exist
> Added 3 missing members to CCAnimateFrameCache

- bindings/GeometryDash.bro
This PR adds mac offsets to existing functions. The classes include `SecretLayer2`, `LevelInfoLayer`, and `FriendsProfilePage`
If there needs to be any changes to this PR such as signatures or issues, let me know so I can make them.
> Update Bindings for a bunch of classes (Mac)

- bindings/GeometryDash.bro
i didn't find either of those but thanks Coloride for win and Firee for mac
> add GJAccountManager::getGJP

- bindings/GeometryDash.bro
- loader/src/ids/LevelBrowserLayer.cpp
- loader/src/ids/LevelInfoLayer.cpp
- loader/test/members/Android.cpp
This PR fixes the Android bindings and gets them to a state where BetterInfo (the most important mod) is fully functional
> Improve Android bindings

- bindings/GeometryDash.bro
This PR adds a lot of mac offsets to 2 classes, multiple in `CreatorLayer`, and one in `DailyLevelPage` as it was missing one.
If there needs to be any changes to this PR, let me know so I can make them.
> Add a lot of mac bindings

- bindings/GeometryDash.bro
One of these (set stat) might be a risk to expose so I'm not 100% sure if you guys want it covered or not
> Added 2 additional methods to GameStatsManager

- bindings/GeometryDash.bro
Added the addresses for 
GJGarageLayer: onPlayerDeathEffect, onPlayerTrail, showCircleWave, showBlackCircleWave 
GJRobotSprite: updateGlowColor
LevelInfoLayer: onBack, onDelete, keyBackClicked
ListButtonBar: switchedPage
Renamed m_unk4DC in PlayerObject to m_hasGlow
> Add some quite epic bindings bro

- bindings/GeometryDash.bro
same as windows except for the first pad
> add android paddings to PlayerObject

- bindings/GeometryDash.bro
> processSelectObjects mac binding

- bindings/GeometryDash.bro
hello I have learned the reversed engineering
> custom song widget members and functions

- bindings/GeometryDash.bro
This PR adds SearchButton
see: it's a button
> Bindings: add SearchButton

- bindings/GeometryDash.bro
* reorder funcs in UserListDelegate because the order was wrong
* add those same functions to FriendsProfilePage
* add getUserList and getStoredUserList to GLM
* change unknown delegate to UserListDelegate in GLM
* add callbacks for most buttons in ProfilePage
let's hope this doesn't break anything!
> add a bunch of bindings

- README.md
Just fix a misspelling - we can't go into 2024 with misspellings!
> "Incompatability" 🚫 "Incompatibility" ✅

- loader/include/Geode/Enums.hpp
- loader/include/Geode/cocos/menu_nodes/CCMenuItem.h
- loader/include/Geode/modify/IDManager.hpp
- adds CommentKeyType values
- fixes a CCMenuItem class member
- fixes IDManager for InfoLayer (it shadows getID)
> Some more 2.2 stuff

- loader/include/Geode/Enums.hpp
> fill in LevelLeaderboardMode enum

- CMakeLists.txt
- installer/mac/Scripts/postinstall
- loader/include/Geode/cocos/base_nodes/CCNode.h
- loader/include/Geode/loader/Mod.hpp
- loader/include/Geode/loader/SettingJsonTest.hpp
- loader/include/Geode/utils/JsonValidation.hpp
- loader/include/Geode/utils/VersionInfo.hpp
- loader/include/Geode/utils/cocos.hpp
- loader/include/Geode/utils/file.hpp
- loader/src/loader/IPC.cpp
- loader/src/loader/Index.cpp
- loader/src/loader/ModImpl.cpp
- loader/src/loader/ModMetadataImpl.cpp
- loader/src/platform/android/console.cpp
- loader/src/ui/internal/list/ModListCell.cpp
- loader/src/ui/internal/list/SearchFilterPopup.cpp
- loader/src/ui/internal/settings/GeodeSettingNode.cpp
- loader/src/ui/nodes/ColorPickPopup.cpp
- loader/src/ui/nodes/MDTextArea.cpp
- loader/src/utils/cocos.cpp
- loader/src/utils/file.cpp
- loader/src/utils/web.cpp
- loader/test/dependency/main.cpp
> remove try blocks

- .github/ISSUE_TEMPLATE/feature-request.yml
- loader/src/internal/crashlog.cpp
This fixes two itty bitty teeny weeny tiny typos :3
> Fix two tiny typos

- loader/src/platform/mac/LoaderImpl.mm
> implement getGameVersion on mac

- loader/include/Geode/cocos/robtop/keyboard_dispatcher/CCKeyboardDispatcher.h
- loader/src/platform/android/input.cpp
- loader/src/platform/android/main.cpp
a little silly thing
requires a version of the android launcher [that supports it](https://github.com/geode-sdk/android-launcher/tree/input). that'll eventually be merged into main
> Implement callbacks for Android keyboard inputs

- loader/src/hooks/ImpostorPlayLayerFix.cpp
Fixes the infamous Impostor PlayLayer bug, which causes issues in many mods with PlayLayer hooks.
> impostor playlayer fix

- loader/src/hooks/LoadingLayer.cpp
> Fix a duplicated node ID

- loader/CMakeLists.txt
I am very intellect at using the GitHub platform
> [Loader] Fix android build

- installer/windows/Language Files/SimpChineseExtra.nsh
- installer/windows/Language Files/TradChineseExtra.nsh
> 文件夾 grammar (thank you @poweredbypie)

- loader/src/cocos2d-ext/CCFileUtils.cpp
Previously, you guys removed the pack then checked if the path is recognized, causing the removed pack to be added as a path. This fix adds a REMOVED_PACKS vector that is used to determine if it is an old removed pack, and then mark it as known so it isn't added back to the path. This vector is then cleared when m_searchPathArray is cleared as well.
> Fix Texture Pack Removal

- loader/include/Geode/Enums.hpp
realized these existed while i was working on a mod
> add to the CommentType enum

- loader/src/ui/nodes/ScrollLayer.cpp
> This should use nodeIsVisible imo

- loader/include/Geode/cocos/misc_nodes/CCMotionStreak.h
> Fix CCMotionStreak member

- .github/workflows/check-changelog.yml
- CHANGELOG.md
> Check for non-ascii characters in changelog.md

- loader/resources/mod.json.in
Add discord and website links to geode.loader mod.json
> Add discord and website links to mod.json

- .github/workflows/build.yml
- installer/windows/installer.nsi
This basically just enables solid LMZA compression, makes the compression dictionary size 64mb and, optimizes the data block.
> Better compression for installer on windows

- loader/src/ui/nodes/MDTextArea.cpp
Kept the old one for compatibility reasons
This has been tested
> New image arguments format

- installer/windows/Language Files/SimpChineseExtra.nsh
- installer/windows/Language Files/TradChineseExtra.nsh
> Update chinese translations

- installer/windows/Language Files/SimpChineseExtra.nsh
simplified/traditional mixup :sob:
> revise chinese translations

- loader/src/platform/windows/crashlogWindow.cpp
you can now restart the game instantly (yay!)
also fixes weird flickering with buttons by redrawing them on resize
> fixing windows crashlog window

- loader/src/ui/mods/popups/FiltersPopup.cpp
> allow dashes in developer name search

- loader/include/Geode/cocos/include/cocos2d.h
- loader/include/Geode/cocos/robtop/special_nodes/CCLightning.h
> Revert "Delete CCLightning header"

- loader/include/Geode/cocos/label_nodes/CCLabelBMFont.h
This may break bindings if merged, so remove the entries from Cocos2d.bro on release
> CCLabelBMFont extra kerning

- installer/windows/Language Files/SpanishInternationalExtra.nsh
_Some_ text is in english, and I decided to translate it. _Hopefully_ I did it right and this text can be used in the installer.
> Translate english text in SpanishInternationalExtra.nsh

- loader/src/server/Server.cpp
- loader/src/ui/mods/list/ModItem.cpp
- loader/src/ui/mods/popups/ModPopup.cpp
- loader/src/ui/mods/sources/ModSource.cpp
- loader/src/ui/mods/sources/ModSource.hpp
See #1148 for more details.
Backported to 2.206
> [V3] Fix mod downloads not using the metadata version to download

- loader/include/Geode/cocos/support/zip_support/ZipUtils.h
- loader/include/Geode/utils/Task.hpp
- loader/include/Geode/utils/cocos.hpp
- loader/src/loader/LoaderImpl.cpp
- loader/src/server/DownloadManager.cpp
> Fix every "succes" spelling mistakes I could find

- installer/windows/Language Files/PortuguesePTExtra.nsh
- installer/windows/installer.nsi
> Added pt-pt

- loader/src/server/Server.cpp
- loader/src/server/Server.hpp
Another zero deletion pull request I guess
> Fix links not appearing on non-installed mods

- loader/include/Geode/utils/file.hpp
> Implement UTF conversion for matjson::Serialize<std::filesystem::path>

- loader/include/Geode/cocos/include/cocos2d.h
- loader/include/Geode/cocos/robtop/sprite_nodes/CCFontSprite.h
- loader/include/Geode/cocos/robtop/sprite_nodes/CCSpriteExtra.h
Not really anything else to these classes
> CCFontSprite and CCSpriteExtra

- loader/include/Geode/cocos/actions/CCActionEase.h
- loader/include/Geode/cocos/support/zip_support/ZipUtils.h
This also includes a change to ZipUtils.h, due to me needing it in a future addition to member tests in bindings.
> CCEaseRateAction custom constructor

- loader/src/hooks/AddExtraKeys.mm
I made this pull request while outside.
> Fix macOS arrow keys

- loader/src/hooks/AndroidSaveFix.cpp
> Android Save Fix

- loader/src/ui/mods/ModsLayer.cpp
- loader/src/ui/mods/list/ModItem.cpp
- loader/src/ui/mods/list/ModList.cpp
- loader/src/ui/mods/sources/ModListSource.hpp
- loader/src/ui/mods/sources/ServerModListSource.cpp
It's nearly May, we should probably hide this by now.
We could maybe reintroduce it in as an archive list, but the website has that anyway.
> Remove Modtober 2024 tab from ModsLayer

- loader/include/Geode/utils/general.hpp
- loader/src/platform/android/util.cpp
- loader/src/platform/ios/util.mm
- loader/src/platform/mac/util.mm
- loader/src/platform/windows/util.cpp
- loader/src/ui/mods/ModsLayer.cpp
this requires an android launcher update btw. my bad
> add safe area api

- .github/scripts/parse-release.py
- .github/workflows/upload-release.yml
- CMakeLists.txt
> Upload release workflow

- loader/include/Geode/loader/Mod.hpp
- loader/src/loader/Log.cpp
- loader/src/loader/Mod.cpp
- loader/src/loader/ModImpl.cpp
- loader/src/loader/ModImpl.hpp
I didn't think I would finish this as quickly as I did, but oh well.
> Add the ability to change a mod's log level

- .github/workflows/build.yml
- loader/CMakeLists.txt
- loader/include/Geode/utils/base64.hpp
- loader/src/utils/base64.cpp
clang-cl is needed for simdutf :P
> Add base64 utils (and switch to clang-cl)

- loader/include/Geode/cocos/sprite_nodes/CCSprite.h
Funny how inheriting CCSprite was broken this entire time.
> CCSprite members

- loader/include/Geode/ui/MDPopup.hpp
- loader/include/Geode/ui/MDTextArea.hpp
- loader/src/loader/SettingNodeV3.cpp
- loader/src/ui/mods/ModsLayer.cpp
- loader/src/ui/nodes/MDPopup.cpp
- loader/src/ui/nodes/MDTextArea.cpp
before
After
(ideal for preventing softlocks on ios)
> The other popup idea

- loader/include/Geode/utils/SeedValue.hpp
> I wanted to add one but cvolton said they wanted too 
so i never did it
as you can see it's been a year and still no formatter 
> maybe one day a 3rd person will come in and actually add it
> add format_as for seedvalues

- loader/src/ui/mods/list/ModDeveloperList.cpp
> Fix ModDeveloperList displaying devs bottom to top

- loader/include/Geode/c++stl/aliastl.hpp
So that I can use pair iterators without having to do stupid shit
> gd::pair for non-Android

- loader/include/Geode/ui/Notification.hpp
- loader/src/ui/nodes/Notification.cpp
> Change notification queue to manually managed array

- .github/workflows/build.yml
ubuntu 24.04 doesnt have clang 20 :|
maybe we should switch to the llvm apt repo soon
> use clang 19 for windows build

- loader/include/Geode/c++stl/gnustl/c++config.h
- loader/include/Geode/c++stl/gnustl/stl_vector.h
- loader/src/platform/android/util.cpp
closes #1330
implements that pr with an iterator instead
> Android vector fix

- installer/windows/Language Files/ItalianExtra.nsh
- installer/windows/installer.nsi
Translations are by @barfowastaken on Discord.
> Add Italian Translations

- loader/src/platform/mac/main.mm
- loader/src/platform/windows/main.cpp
Just word it slightly better. 
- Less verbosity
- State that **Geometry Dash** is outdated, not just "Your game"
- Reiterate the version needed when told to update
> Better outdated warning

- cmake/Platform.cmake
- loader/src/platform/ios/util.mm
- loader/src/platform/mac/util.mm
love all my supporters  it's time
> cocos2d::CCImage::saveToFile on macOS and iOS

- loader/include/Geode/loader/ModMetadata.hpp
- loader/src/loader/ModMetadataImpl.cpp
- loader/src/loader/ModMetadataImpl.hpp
Forgot to include this in #1492
> Remove unused force-load-priority property
