- include/cocos/cocos2dx/platform/win32/CCApplication.h
- include/cocos/cocos2dx/robtop/keyboard_dispatcher/CCKeyboardDelegate.h
Adds controller keybinds to the enum and getControllerConnected() to the Windows CCAppliation header. Also of note is that the game actually calls PlatformToolbox::isControllerConnected() in reality, which gets inlined on Windows to access the CCApplication member directly (which I don't have the proper location for).
Basically an equivalent of this https://github.com/HJfod/cocos-headers/pull/16
> Controller support

- bindings/GeometryDash.bro
- include/codegen-base/HeaderBase.hpp
The 10 or so cells with updateBGColor pointing to the same offset are not a copy paste error, in these cases it really is a different function on Android but it's all merged into one on Windows because all of these execute the exact same code
Delegates in GLM are taken from Wylie's GD decomp and verified to be mostly accurate (I didn't test every single one but I did a quick test of about a half of them)
also this one actually compiles which i think is an improvement from the last pr i made
> even more headers

- bindings/GeometryDash.bro
this addresses any crashes caused by accessing the 3 dicts in GM and apart from fixing these being misaligned, it also fixes the misalignment of the 2 members that follow m_smoothFix
idk if this works on mac i just made the same edits to the mac offsets that i did for the windows ones
m_adTimer, m_adCache and m_unknownDouble might (still?) be misaligned, these were not tested, as i do not have ads in the steam version of geometry dash
> improved gamemanager

- Geode.cmake
- cmake/MacOS.cmake
This fix the problem of mod not compiling on mac m1,
Although there's one thing to note,
If you have the following structure
```
root
|- CMakeLists.txt
|- sub-1
|- CMakeLists.txt
|- sub-2
|- CMakeLists.txt
```
It's advised to put this in the `root`'s CMakeLists.txt
```cmake
find_path(GEODE_SDK_PATH
NAMES Geode.cmake
PATHS $ENV{GEODE_SUITE}/sdk /Users/Shared/Geode/suite/sdk /usr/local/geode/sdk
DOC "Geode SDK path."
REQUIRED
)
include(${GEODE_SDK_PATH}/Geode.cmake)
```
If you decided to put it in both `sub-1` and `sub-2` CMakeLists.txt, It will cause the `sub-1` to compile as arm64 and other subdirectory as x86_64 (Don't ask me why this happened, i don't know and this is weird)
> fix(cmake): Not working on mac platform

- CMakeLists.txt
- codegen/CMakeLists.txt
this is necessary in cross compilation enviroments, such as compiling for android or cross compiling to windows on linux, since we want the codegen executable to be of the current system, not the cross compilation target
> switch to using ExternalProject for codegen

- loader/include/Geode/utils/file.hpp
- loader/src/utils/file.cpp
The returned bool indicates whether the directory was created or not, not whether it *failed* to create it (it might've already existed, which is not a fail, yet that'd still return false, because it didn't need to create the directory)
> Fix wrong usage of create_directory/create_directories API

- bindings/GeometryDash.bro
From my findings, legacy levels are indicated if this bool is false. If it is, GD will default to extracting the metering from the AudioEffectsLayer rather than using GameSoundManager.
I say this is likely a way of indicating a legacy mode because this can be found in all levels which were made before 2.1.
> Added the supported metering variable to PlayLayer

- bindings/GeometryDash.bro
Added `init()` function for `KeysLayer` class. (Windows only)
> Add `KeysLayer::init` binding

- CMakeLists.txt
Fixes an issue where FMT_CONSTEVAL isn't set properly when enabling GEODE_DISABLE_FMT_CONSTEVAL.
> fix GEODE_DISABLE_FMT_CONSTEVAL

- bindings/GeometryDash.bro
`PlayerObject::collidedWithObject(float, GameObject *)` is inlined on Windows so we should implement it here as well.
> Fix bindings

- codegen/src/Main.cpp
- codegen/src/Shared.hpp
This is the only place where `<direct.h>` is used, and it's entirely unnecessary because of `ghc::filesystem`.
> Use `fs::current_path` over `chdir`

- bindings/GeometryDash.bro
- loader/include/Geode/cocos/robtop/scene_nodes/CCSceneTransitionDelegate.h
Compiling against these updated bindings fixes crashes caused by CreatorLayer:sceneWillResume
> add CreatorLayer delegates

- bindings/GeometryDash.bro
special thanks to ninxout crystal client for mac addresses
this adds the required addresses for 3 functions in EditLevelLayer and properly sets the type of 1 member in PlayLayer
> add bindings for robtop bot

- bindings/Cocos2d.bro
- bindings/GeometryDash.bro
- loader/test/members/MacOS.cpp
- loader/test/members/Windows.cpp
This PR adds Mac addresses for several functions and fixes header alignment of GLM and GSM on Mac.
GSM->m_playerStats might still be misaligned on Mac, as it is stuck between 2 pads and I haven't verified whether that specific dict contains the correct data
> Bi additions 5

- loader/src/platform/windows/LoaderImpl.cpp
Remove SetThreadDescription calls to restore Windows 7 compatibility
> Remove SetThreadDescription calls

- bindings/GeometryDash.bro
Note for other occurences, if it's a node and it has 2 floats as fields, 99% of the time it's rob adding the accurate width and height rather than fixing the content size
> Replaced the unknown in Slider with the accurate name

- bindings/GeometryDash.bro
This PR adds the `SecretLayer2` class, which inherits similar classes to `SecretLayer4`.
If there needs to be any changes to this PR, let me know so I can make them.
Credits to @Jouca for the 2 offsets; `onSubmit` & `updateSearchLabel`. The other funcs: `init`, `showCompletedLevel`, `create` by me.
> Add SecretLayer2 class to bindings

- bindings/GeometryDash.bro
This PR updates the labels in LevelInfoLayer, so they are properly descriptive of their purpose. It also adds LevelInfoLayer::updateLabelValues() (windows & mac) and SpeedObject::create() (windows only), both functions have been tested to work
> Update LevelInfoLayer bindings

- bindings/GeometryDash.bro
This PR adds more functions to the `EndLevelLayer`, and also adds inherits to `CCLayer` (for hooking `customSetup` for example) 
If there needs to be any changes to this PR such as signatures or issues, let me know so I can make them.
> Update EndLevelLayer class bindings

- bindings/GeometryDash.bro
This PR adds bindings for PauseLayer buttons and fixes the one missing button in EditorPauseLayer on Mac
> Bindings: PauseLayer buttons

- bindings/GeometryDash.bro
This PR fixes misaligned LLM header that breaks GDShare importing on both Mac and Windows. I also recommend recompiling GDShare itself against these fixed headers to fix this feature, as it currently either does nothing or crashes the game for users.
> Fix misaligned LLM header

- bindings/GeometryDash.bro
This commit is dedicated to Crystal Client ninXout Windows 7, Windows 8, Windows 9, Windows 10, and Windows 11
> Add GJGameLevel::savePercentage

- loader/src/utils/web.cpp
Follow redirects was enabled for basically all request types except web::fetch, web::fetchJSON, web::fetchBytes. It makes sense to have it enabled for those too :)
> add follow redirects to all web::fetch functions

- bindings/GeometryDash.bro
This PR adds mac offsets to 2 functions in `SimplePlayer` class, `setOpacity` and `setFrames`.
If there needs to be any changes to this PR, let me know so I can make them.
> Update SimplePlayer bindings

- .github/workflows/test-offsets.yml
This way you prevent useless offset tests when there were no changes made to the bindings
> Added a filter to only test offsets on bindings

- loader/src/ui/nodes/TextArea.cpp
Simply put, alignment had no default assignment, causing undefined behavior, this also revealed some bad anchor points which could be optimized
> Fixed alignment issues caused by unallocated memory in textarea

- bindings/GeometryDash.bro
- loader/src/loader/Index.cpp
This little blue guy doesn't appear if you have updates available only on disabled mods
Also added LevelEditorLayer::getNextColorChannel to windows and changed its return type to int
> Do not show the update notice for disabled mods + one binding

- bindings/GeometryDash.bro
This PR fixes Cvolton/betterinfo-geode#3, which is caused by a bindings error in Geode
> fix MoreSearchLayer::create on Mac

- loader/src/hooks/CCTextInputNode.cpp
The vanilla code doesn't work for scenarios in which a `CCTextInputNode` has multiple ancestors at different positions because it only looks at the direct parent. This adds a patch to fix that.
> Make `CCTextInputNode` work in nested hierarchies

- loader/src/hooks/CCTextInputNode.cpp
Sometimes this is null (happened on a custom CCTextInputNode for me) and the vanilla code does a check so let's as well.
> Add null check for `m_delegate`

- loader/src/utils/web.cpp
By default, when an HTTP error code is sent (4XX or 5XX), this will usually result in the message `Fetch failed: HTTP response code said error`
To resolve this, FAILONERROR for curl opts is disabled, and HTTP error codes are handled manually. Instead of the generic response given before (Which doesn't tell anything about what really happened), the response is given instead.
If there needs to be any changes to this PR, let me know so I can make them.
> Handle HTTP error responses

- loader/src/platform/windows/crashlog.cpp
- loader/src/platform/windows/ehdata_structs.hpp
When a C++ exception was thrown from a mod or from Geometry Dash itself, rather than displaying the error code `0xE06D7363`, attempt to also display the error message of the exception.
> Display messages of unhandled c++ exceptions on Windows

- bindings/GeometryDash.bro
add windows addresses for LevelTools::getAudioFileName, LevelTools::getAudioTitle, LevelTools::artistForAudio and LevelTools::urlForAudio
> Add windows addresses for some LevelTools functions

- CMakeLists.txt
- loader/include/Geode/loader/Log.hpp
- loader/include/Geode/utils/VersionInfo.hpp
- loader/src/load.cpp
- loader/src/loader/LoaderImpl.cpp
- loader/src/loader/Log.cpp
- loader/src/loader/LogImpl.hpp
- loader/src/loader/ModImpl.cpp
- loader/src/platform/mac/LoaderImpl.mm
- loader/src/platform/windows/LoaderImpl.cpp
- loader/src/ui/nodes/MDTextArea.cpp
- loader/src/utils/VersionInfo.cpp
Fixes #369 
- removes LogComponents, now logs just get formatted into a string and saved like that
- Now to define formatting of own type, use fmtlib's api (either format_as or fmt::formatter, see their docs!)
- Breaks ABI (wowie!)
- Usage wise, your code stays the exact same. unless you had defined your own `parser` overload
> Refactor logging internals

- loader/src/platform/windows/crashlog.cpp
- loader/src/platform/windows/ehdata_structs.hpp
this PR brings a small cleanup to `ehdata_structs.hpp`, changes the format of the unhandled exception message to include the demangled name of the type that was thrown, and makes the handler work on 64-bit windows.
> c++ exception handler improvements + 64-bit compatibility

- loader/src/platform/android/util.cpp
This PR fixes a crash that would occur if you used any cocos functions in the callbacks from file::openFile.
> Run file IO callbacks on cocos thread on Android

- loader/include/Geode/loader/Loader.hpp
- loader/include/Geode/loader/Mod.hpp
- loader/src/loader/Loader.cpp
- loader/src/loader/LoaderImpl.cpp
- loader/src/loader/LoaderImpl.hpp
- loader/src/loader/Mod.cpp
- loader/src/loader/ModImpl.cpp
- loader/src/loader/ModImpl.hpp
- loader/src/platform/android/LoaderImpl.cpp
- loader/src/platform/ios/LoaderImpl.cpp
- loader/src/platform/mac/LoaderImpl.mm
- loader/src/platform/windows/LoaderImpl.cpp
- loader/test/main/main.cpp
This PR adds API methods for accessing loader or mod-specific **launch arguments** passed in via the command-line when running the game. For example, a Steam user can modify their launch arguments in the "Launch Options" tab under "Properties".
Specifically, on both `Loader` and `Mod`, four new methods are accessible in the public API:
- `std::vector<std::string> getLaunchArgumentNames()`
- `bool hasLaunchArgument(std::string_view const name)`
- `std::optional<std::string> getLaunchArgument(std::string_view const name)`
- `bool getLaunchBool(std::string_view const name)`
The API does not provide access to *every* argument passed in via the command-line. Instead, the loader only reads arguments that are prefixed with `-geode:`. The full format is `-geode:argName=value`.
For example, …
> Launch Arguments

- loader/src/ui/nodes/MDTextArea.cpp
Also should be easy to add other arguments for the sprite now if needed. 
Example use:
`![link](frame:gj_linkBtn_001.png&scale:0.5)`
> Add sprite scaling for MDTextArea

- loader/src/hooks/MessageBoxFix.cpp
instead of copying function over, patch call ds:MessageBoxW to call ds:MessageBoxA
this is better because now there's 2 different functions for GLFW error handling(???) and they have different calling conventions
before https://i.imgur.com/HCp7d1v.png
after https://i.imgur.com/zzPELWK.png
> update fix for GLFW error handler to 2.204

- .github/actions/setup-dump-sym/action.yml
- .github/workflows/build.yml
- CMakeLists.txt
- loader/CMakeLists.txt
- loader/src/loader/LoaderImpl.cpp
- loader/src/platform/android/crashlog.cpp
as an alternative to the current (very broken) crash handler. ideally the original crash handler would be fixed, but this is a workable solution for now. just adds a lot of complexity to the act of sharing crash dumps
also: `-DGEODE_USE_BREAKPAD=OFF` will disable it for a build, adding `--geode:disable-crash-handler` will disable it for a session
- would be good to have some sort of symbol server to make the process of resolving symbol dumps a little easier
- breakpad stores dumps with a very strange naming system, which may be a little hard to find. imo the crash popup should redirect people to export the last crash
> Use Breakpad for crash reports on Android 

- loader/include/Geode/loader/Log.hpp
- loader/src/load.cpp
- loader/src/loader/LoaderImpl.cpp
- loader/src/loader/Log.cpp
- loader/src/loader/LogImpl.hpp
- loader/src/loader/console.hpp
- loader/src/platform/android/console.cpp
- loader/src/platform/mac/LoaderImpl.mm
- loader/src/platform/windows/console.cpp
generally works better with debuggers and such on windows now
- console no longer opened/closed in run-time (only opened on startup if enabled)
- log should be fully thread safe now (?)
- windows: the console can now attach to the parent console if ran from cmd or a debugger or whatever
- windows: stdin/stdout are no longer redirected to console, logger uses WriteFile instead
- windows: stdout/stderr are now redirected to logger
> Refactor console handling

- loader/include/Geode/cocos/platform/CCPlatformMacros.h
When opening any .cpp file that includes cocos headers in geode you get the following annoying errors caused by `CC_FORMAT_PRINTF` macro, used in some headers like CCStringh or Common.h
These errors are only part of intellisense and not part of the actual compilation. This is due to the fact that in intellisense `CC_FORMAT_PRINTF` ends up undefined. Just as the comment above says, intellisense defines `__has_attribute` but not `__has__attribute(format)`.
After doing [some research](https://stackoverflow.com/questions/2354784/attribute-formatprintf-1-2-for-msvc) the format attribute doesn't seem to be supported by MSVC anyway so it's better to always define it as an empty macro. 
After the fix, the macro is properly defined as empty and the erros disappear
> Fix Visual Studio 2022 Intellisense errors

- CMakeLists.txt
This pr fixes cmake treating precompiled headers as C files. CMake generates .c and .h files instead of .cxx and .hxx which causes a compiler error, since precompiled headers get compiled in C mode. So far it seems like I'm the only one that has experienced this issue. The proposed solution is a common practice in cmake, as seen by the [1.1k github search results](https://github.com/search?q=%22target_precompile_headers%22+%3C%24%3CCOMPILE_LANGUAGE%3ACXX%3E+language%3ACMAKE&type=code)
> fix pch being treated as c files

- loader/src/platform/windows/console.cpp
These lines cause Geode to crash (without any crash logs) when launching Geometry Dash through the terminal. Or `wine GeometryDash.exe`
Removing these lines fixes the issue, though @cgytrus requested that @dankmeme01 & @matcool (also themselves) test it.
Let me know if this causes any issues.
> Fix Wine crashing when launching via terminal

- loader/src/ui/internal/GeodeUI.cpp
Currently, "Report an Issue" button, which can be found in the `ModInfoPopup` if `mod.json` contains `issues` property, doesn't do anything useful except opening crashlog directory. This changes it to actually open the specified URL in browser / crashlogs directory, instead of both buttons having the same action.
> Implement "Report Issue" button

- loader/include/Geode/c++stl/aliastl.hpp
- loader/include/Geode/c++stl/gdstdlib.hpp
- loader/include/Geode/c++stl/msvc/allocator.hpp
- loader/include/Geode/c++stl/msvc/umap.hpp
- loader/include/Geode/c++stl/msvc/uset.hpp
- loader/include/Geode/c++stl/msvc/xhash.hpp
- loader/include/Geode/c++stl/msvcstl.hpp
- loader/src/platform/windows/gdstdlib.cpp
Fix for #633, includes `unordered_map`, `unordered_set` from the latest MSVC STL, adapted to match the layout of STL 2013, and to work standalone. Basic operations such as insertion, removal and lookup have been tested and confirmed to work without problems.
Additionally includes an implementation of `allocator` which is required for fixing memory related crashes.  Other containers not  subject to this PR such as `vector`, `map`, `set` might require the same treatment.
> MSVC Fixups

- loader/src/ui/nodes/MDTextArea.cpp
This was pissing me off so I fixed it
> [Loader] Correct rendering of soft line breaks in MDTextArea

- loader/CMakeLists.txt
I think CMake is trying to link zlib from the host system? This prevents it from doing that.
This also causes a fun new CMake warning when configuring for whatever reason.
> [Loader] Enable 'MZ_FORCE_FETCH_LIBS'

- loader/include/Geode/utils/cocos.hpp
`i` is always >= 0 because it is unsigned. This causes crashes if no children are found before reaching 0.
> getChildOfType negative indices: size_t is unsigned

- loader/src/hooks/LoadingLayer.cpp
The actual reason lies in the loader implementation, which for some reason can sometimes count up the `m_refreshedModCount` twice for some mods which are disabled.
This small change checks the actual loaded mod count instead of relying on an incorrect `LoaderImpl` member and fixes issue #687.
> Fix loading bar going out of bounds

- loader/include/Geode/cocos/include/ccTypes.h
Fixed `ccHSVValue` because it is not correct at the moment.
> Fix `ccHSVValue`

- loader/include/Geode/utils/cocos.hpp
- loader/src/utils/cocos.cpp
Tentative function names. Suggestions are very much welcome.
This is in the case of a sprite having image that is not part of a texture frame.
> `geode::cocos::isSpriteName` and `geode::cocos::getChildBySpriteName`

- loader/include/Geode/loader/Loader.hpp
- loader/src/loader/Loader.cpp
Can be useful to some mods that have `"gd": "*"` in their `mod.json`
> Make getGameVersion public

- loader/src/ui/internal/GeodeUI.cpp
changes the `geode::openIssueReportPopup` function to show the contents of the `info` key from `mod.json` instead of a hardcoded message
> show info key from mod.json in geode::openIssueReportPopup

- loader/src/hooks/MenuLayer.cpp
- loader/src/ui/mods/GeodeStyle.cpp
- loader/src/ui/mods/GeodeStyle.hpp
- loader/src/ui/mods/list/ModDeveloperItem.cpp
- loader/src/ui/mods/list/ModDeveloperItem.hpp
- loader/src/ui/mods/list/ModDeveloperList.cpp
- loader/src/ui/mods/list/ModDeveloperList.hpp
- loader/src/ui/mods/list/ModItem.cpp
- loader/src/ui/mods/popups/DevPopup.cpp
- loader/src/ui/mods/popups/DevPopup.hpp
- loader/src/ui/mods/popups/ModErrorPopup.cpp
- loader/src/ui/mods/settings/ModSettingsPopup.cpp
This PR fixes a ton of minor issues with the UI, including:
- Fixes misaligned Download counts due to non absolute button widths
- Fixes misaligned checkboxes due to content size changing from different sprites
- Replaces the exclamation point on the geode logo with the vanilla one
- Fixes the incorrect mod settings popup size that would get clipped on the top otherwise
- Fixes the oddly short mod problems popup
- Fixes small gap with border on mod settings
This PR also revamps the mod developer list to use a list rather than add a bunch of labels for each developer.
> UI Fixes and Revamped Developer List

- .github/actions/build-debug-info-post/action.yml
- .github/actions/build-debug-info/action.yml
- .github/actions/setup-cache/action.yml
- .github/actions/setup-cli/action.yml
- .github/actions/setup-ninja/action.yml
- .github/workflows/build.yml
- moved some stuff to separate actions called from the main workflow
- separated the `build` job into 3 separate jobs for each platform
this is mainly to get rid of the many many platform conditions in the workflow, making each individual platform's build process easier to read and making the workflow nicer to look at in github actions' ui
> Cleanup the build.yml CI workflow

- loader/src/ui/nodes/TextInput.cpp
before this PR, when using textalign center there was no padding for text that reached the sides of the input box:
and when using textalign left there was padding on the left but on the right it overflowed.
this PR fixes both cases to this:
before this PR, setWidth doesn't set the width of the TextInput node. So if you set the width to a number smaller than the original width, it'd look like this:
and if you set the width to a number larger than the original width:
this PR fixes that
> Fixes for TextInput

- loader/include/Geode/utils/web.hpp
- loader/src/utils/web.cpp
Currently web mods need to check for pointers to prevent hook recursion. But to prevent the request from being thrown out you also need to copy it. This makes it so there can never be 2 web mods active at the same time.
> Added IDs to web request to prevent incompatibilities between web mods

- loader/src/platform/windows/main.cpp
The game crashes if launched from command prompt from a directory other than the game's directory.
This should fix the CWD back to the GD directory.
I need this so I can easily run GD from a batch script after compiling my mod.
> Fixing current working directory on startup

- loader/include/Geode/c++stl/gnustl.hpp
- loader/include/Geode/c++stl/gnustl/alloc_traits.h
- loader/include/Geode/c++stl/gnustl/allocator.h
- loader/include/Geode/c++stl/gnustl/c++allocator.hpp
- loader/include/Geode/c++stl/gnustl/c++config-arm64.h
- loader/include/Geode/c++stl/gnustl/c++config-armeabi-v7a.h
- loader/include/Geode/c++stl/gnustl/c++config.h
- loader/include/Geode/c++stl/gnustl/exception_defines.h
- loader/include/Geode/c++stl/gnustl/ext/aligned_buffer.h
- loader/include/Geode/c++stl/gnustl/ext/alloc_traits.h
- loader/include/Geode/c++stl/gnustl/ext/new_allocator.h
- loader/include/Geode/c++stl/gnustl/ext/numeric_traits.h
- loader/include/Geode/c++stl/gnustl/functional_hash.h
- loader/include/Geode/c++stl/gnustl/hash_bytes.h
- loader/include/Geode/c++stl/gnustl/hash_specialization.hpp
- loader/include/Geode/c++stl/gnustl/hashtable.h
- loader/include/Geode/c++stl/gnustl/hashtable_policy.h
- loader/include/Geode/c++stl/gnustl/memoryfwd.h
- loader/include/Geode/c++stl/gnustl/new_allocator.h
- loader/include/Geode/c++stl/gnustl/ptr_traits.h
- loader/include/Geode/c++stl/gnustl/range_access.h
- loader/include/Geode/c++stl/gnustl/stl_function.h
- loader/include/Geode/c++stl/gnustl/type_traits.h
- loader/include/Geode/c++stl/gnustl/unordered_map.h
- loader/include/Geode/c++stl/gnustl/unordered_map.hpp
- loader/include/Geode/c++stl/gnustl/unordered_set.h
- loader/include/Geode/c++stl/gnustl/unordered_set.hpp
> add android umap and set; bunch of gnustl headers

- loader/include/Geode/c++stl/gnustl/hashtable.h
`integral_constant` wasn't defined, so using one from std fixes it.
it should be exactly the same across different standard libraries, so no problems there.
> fix gd::umap/uset copy constructor for gnustl

- loader/src/ids/MenuLayer.cpp
The menu had no padding added so it was right up against the screen, which is ugly
> Fix bad 'top-right-menu' placement in MenuLayer (Node IDs)

- loader/include/Geode/utils/cocos.hpp
The old code works fine if you don't use the return value but just in case someone does uses it (me)
> fix `CCArrayExt::pop_back()` `ret` variable not being a pointer

- loader/src/server/Server.cpp
- loader/src/ui/mods/list/ModItem.cpp
- loader/src/ui/mods/popups/ModPopup.cpp
- loader/src/ui/mods/sources/ModSource.cpp
- loader/src/ui/mods/sources/ModSource.hpp
Currently, mods fetch mod metadata from /v1/mods/{id}/latest version, if no version is passed in ModDownloadManager::startDownload(). 
At the same time, this request doesn't include the current GD version as a query param, so it can (and will) fetch mods from incompatible game versions.
Fix is adding this query param as a failsafe and using the mod metadata to download, wherever possible.
We also have to backport this fix to v3 quite fast
> Fix mod downloads not using the metadata version to download

- loader/include/Geode/utils/web.hpp
- loader/src/utils/web.cpp
Because there can be multiple headers with the same name, for example Set-Cookie (which was the main motivation for this change)
Also it's probably terrible idk (although the game didn't explode when I tried to use it and it actually worked)
> Updated the headers map in WebRequest and WebResponse to accept multiple headers with the same name

- EULA
Please ignore the fact I misspelled "misspelling" in the commit that fixes the misspelling contained inside of the Geode SDK End User License Agreement.
> fix 1 (one) misspelling in the End User License Agreement (EULA)

- loader/resources/mod.json.in
- loader/src/load.cpp
- loader/src/loader/LoaderImpl.cpp
- loader/src/loader/Log.cpp
- loader/src/loader/LogImpl.hpp
- loader/src/loader/updater.cpp
- loader/src/platform/mac/LoaderImpl.mm
- loader/src/platform/windows/console.cpp
This PR implements log levels, which are configurable from in-game in the Geode settings.
- There are separate log levels for the platform console and for the log files
- platform console default: info
- log file default: warn
- To achieve this result, I had to play around in geodeEntry(), and moved the Logger::setup() after the internal loader mod is setup, since we need access to the mod settings.
- To assure no logs are lost, I still stored the logs in Logger::m_logs, and spit them out when calling Logger::setup()
- I also changed log levels for some messages Geode logs when loading mods
- Most specific messages ("unzipping file", "Loading binary", "Loading hook ...") were set to debug
- Most general level messages ("Loading mod x", "Loading resources", "Setting up crash handler", ...) …
> Log levels

- loader/include/Geode/cocos/particle_nodes/CCParticleSystemQuad.h
> Make ParticleStruct constructable

- loader/src/hooks/CompileShaderFix.cpp
Mat told me to use addresser, but CCGLProgram::compileShader is a private function
> Add CCGLProgram::compileShader patches to Android and macOS

- loader/include/Geode/utils/ranges.hpp
I suspect I will find five more issues in `geode::utils::ranges` by next week
> Fix ranges::min and ranges::max errors

- loader/src/loader/SettingNodeV3.hpp
- loader/src/ui/mods/ModsLayer.cpp
- loader/src/ui/mods/list/ModItem.cpp
- loader/src/ui/mods/popups/ModPopup.cpp
On every setting update (commited or not), updateState would be called in ModsLayer, ModPopup (if it's active), and all ModItems. This obviously led to bad performance.
This PR just checks if the value change is commited before calling updateState on ModsLayer, ModItem and ModPopup
> Optimize setting value changes

- loader/src/ui/mods/list/ModDeveloperList.cpp
- loader/src/ui/mods/popups/ModPopup.cpp
- Use `SimpleAxisLayout` for `ModDeveloperList`, fixes #953 
- Set link buttons as disabled if mod doesn't have the specific link to disable the button animation, fixes #955
> Random fixes for ModsLayer

- loader/include/Geode/utils/web.hpp
- loader/src/platform/android/util.cpp
Opens a browser in the launcher activity, which would prevent the game from closing.
Useful for cases where mod needs user to do something on a webpage and then return back (e.g. OAuth with local webserver)
Requires https://github.com/geode-sdk/android-launcher/pull/37
> make geode::utils::web::openLinkInBrowser open webview on android

- loader/src/cocos2d-ext/SimpleAxisLayout.cpp
- loader/src/ui/mods/ModsLayer.cpp
- loader/src/ui/mods/list/ModDeveloperItem.cpp
- loader/src/ui/mods/list/ModItem.cpp
- loader/src/ui/mods/list/ModList.cpp
- loader/src/ui/mods/list/ModProblemList.cpp
- Switch most AxisLayouts to SimpleAxisLayouts, excluding a few that may need a better alternative
- Clean up some node positioning and sizing
- Use only short modtober badge to remedy some scaling issues. 
These changes also slightly improve the performance of the UI, as AxisLayouts are expensive when updating.
> Switch almost all AxisLayouts to SimpleAxisLayouts

- loader/include/Geode/ui/LazySprite.hpp
- loader/src/ui/GeodeUI.cpp
- loader/src/ui/nodes/LazySprite.cpp
Adds a new class `geode::LazySprite`, which has APIs for loading an image from the internet, from a file, or from binary data.
Performs as much processing as possible in a background thread, to avoid freezes, and uses a lightweight threadpool, hence it's recommended that all mod developers who manually create images should use this class instead.
TODO: more docstrings and a docs page
> Lazy loaded sprite

- loader/src/ui/nodes/TextInput.cpp
This converts the touch to it's position relative to the parent scale if CCTextInputNode is within geode::TextInput. This resolves the issue where tapping/clicking on the input to change cursor pos is inaccurate.
> Fix geode::TextInput not handling scale properly for touch

- installer/linux/install.sh
- fixes installer not checking for jq (but still depending on it)
- fixes invalid internal return codes (they're unsigned integers)
- improves syntax of checking if a command succeeded
> linux installer fixes

- loader/include/Geode/cocos/base_nodes/CCNode.h
- loader/include/Geode/utils/cocos.hpp
The free function `getChild`, copied into CCNode as `CCNode::getChildByIndex`, in a similar fashion to how `getChildOfType` was moved into CCNode as `CCNode::getChildByType`.
On the next major release, I would recommend removing the free function `getChild` (just like `getChildOfType` was removed), and potentially maybe renaming `CCNode::getChildByIndex` to `CCNode::getChild`; I chose not to name it like so now because it seems to break compilation on mods that use the free getChild function, without qualifying it like `::getChild`, unless, of course, you think `CCNode::getChildByIndex` is a better name than `CCNode::getChild` and can stay.
> add CCNode::getChildByIndex
